#!/bin/bash

if [ ! -d "build" ]
then
 echo "Creating build directory."
 mkdir build ; echo "!.gitignore" > build/.gitignore
fi

rm build/Galvanic
cd build
cmake ..
make

cd ..
ls -lah build/Galvanic
