#!/bin/bash


DIR="$(dirname $(readlink -f $0))"
echo "Changing to root folder $DIR"
cd $DIR

if [ ! -d "build" ]
then
 echo "Creating build directory."
 mkdir build ; echo "!.gitignore" > build/.gitignore
fi

rm build/Galvanic
cd build
cmake ..
make

cd ..
ls -lah build/Galvanic
